
package rs.ac.uns.ftn.xws.cbs.centralna_banka;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-03-14T14:45:44.066+01:00
 * Generated source version: 2.6.5
 * 
 */
 
public class CentralnaBankaPort_CentralnaBankaPort_Server{

    protected CentralnaBankaPort_CentralnaBankaPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CentralnaBankaPortImpl();
        String address = "http://localhost:8080/centralna_banka";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CentralnaBankaPort_CentralnaBankaPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
