
package rs.ac.uns.ftn.xws.cbs.centralna_banka;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import rs.ac.uns.ftn.xws.cbs.mt102.Mt102;
import rs.ac.uns.ftn.xws.cbs.mt103.Mt103;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-03-27T14:30:46.562+01:00
 * Generated source version: 2.6.5
 * 
 */
public final class CentralnaBanka_CentralnaBanka_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ftn.uns.ac.rs/xws/cbs/centralna_banka", "CentralnaBankaService");

    private CentralnaBanka_CentralnaBanka_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CentralnaBankaService.WSDL_LOCATION;
        URL wsdlLocation = new URL("http://localhost:8080/xws-centralna_banka/CentralnaBankaService?wsdl");
		wsdlURL=wsdlLocation;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CentralnaBankaService ss = new CentralnaBankaService(wsdlURL, SERVICE_NAME);
        CentralnaBanka port = ss.getCentralnaBanka();  
        
        {
        System.out.println("Invoking primiMT103...");
        rs.ac.uns.ftn.xws.cbs.mt103.Mt103 _primiMT103_mt103 = new Mt103();
        _primiMT103_mt103.setIdPoruke("123456789123456798");
        port.primiMT103(_primiMT103_mt103);


        }
        {
        System.out.println("Invoking primiMT102...");
        rs.ac.uns.ftn.xws.cbs.mt102.Mt102 _primiMT102_mt102 = new Mt102();
        port.primiMT102(_primiMT102_mt102);


        }

        System.exit(0);
    }

}
