
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package rs.ac.uns.ftn.xws.cbs.centralna_banka;

import java.util.logging.Logger;

import singleton.MainCentralBankProcessor;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-03-27T14:30:46.605+01:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "CentralnaBankaService",
                      portName = "CentralnaBanka",
                      targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/centralna_banka",
                      endpointInterface = "rs.ac.uns.ftn.xws.cbs.centralna_banka.CentralnaBanka")
                      
public class CentralnaBankaImpl implements CentralnaBanka {

    private static final Logger LOG = Logger.getLogger(CentralnaBankaImpl.class.getName());
    
    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.centralna_banka.CentralnaBanka#primiMT103(rs.ac.uns.ftn.xws.cbs.mt103.Mt103  mt103 )*
     */
    public void primiMT103(rs.ac.uns.ftn.xws.cbs.mt103.Mt103 mt103) { 
        LOG.info("Executing operation primiMT103");
        try {
        	
			MainCentralBankProcessor.getInstance().process(mt103);
			           
	    } catch (java.lang.Exception ex) {
	        ex.printStackTrace();
	        throw new RuntimeException(ex);
	    }
	}

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.centralna_banka.CentralnaBanka#primiMT102(rs.ac.uns.ftn.xws.cbs.mt102.Mt102  mt102 )*
     */
    public void primiMT102(rs.ac.uns.ftn.xws.cbs.mt102.Mt102 mt102) { 
        LOG.info("Executing operation primiMT102");
        try {
        	
        	MainCentralBankProcessor.getInstance().process(mt102);
        	
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
}
