
package rs.ac.uns.ftn.xws.cbs.centralna_banka;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-23T18:37:40.769+02:00
 * Generated source version: 2.6.5
 * 
 */
 
public class XWSCentralnaBanka_XWSCentralnaBankaPort_Server{

    protected XWSCentralnaBanka_XWSCentralnaBankaPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new XWSCentralnaBankaImpl();
        String address = "http://localhost:9090/CentralnaBanka";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new XWSCentralnaBanka_XWSCentralnaBankaPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
