
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package rs.ac.uns.ftn.xws.cbs.centralna_banka;

import java.util.logging.Logger;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import singleton.MainCentralBankProcessor;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-23T18:37:40.751+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.ejb.Stateless
@javax.jws.WebService(
                      serviceName = "XWSCentralnaBankaService",
                      portName = "XWSCentralnaBankaPort",
                      targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/centralna_banka",
                      wsdlLocation = "WEB-INF/xml/XWSCentralnaBanka.wsdl",
                      endpointInterface = "rs.ac.uns.ftn.xws.cbs.centralna_banka.XWSCentralnaBanka")
                      
public class XWSCentralnaBankaImpl implements XWSCentralnaBanka {

    private static final Logger LOG = Logger.getLogger(XWSCentralnaBankaImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.centralna_banka.XWSCentralnaBanka#primiMT102(rs.ac.uns.ftn.xws.cbs.mt102.Mt102  mt102 )*
     */
    public void primiMT102(rs.ac.uns.ftn.xws.cbs.mt102.Mt102 mt102) { 
        LOG.info("Executing operation primiMT102");
        System.out.println(mt102);
        try {
        	MainCentralBankProcessor.getInstance().process(mt102);
        	System.out.println("Processed MT102: "+mt102);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.centralna_banka.XWSCentralnaBanka#primiMT103(rs.ac.uns.ftn.xws.cbs.mt103.Mt103  mt103 )*
     */
    public void primiMT103(rs.ac.uns.ftn.xws.cbs.mt103.Mt103 mt103) { 
        LOG.info("Executing operation primiMT103");
        System.out.println(mt103);
        try {
        	MainCentralBankProcessor.getInstance().process(mt103);
        	System.out.println("Processed MT103: "+mt103);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
