package rs.ac.uns.ftn.xws.cbs.centralna_banka;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-23T18:37:40.772+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebServiceClient(name = "XWSCentralnaBankaService", 
                  wsdlLocation = "/home/nikola/workspace/xws/xws-cbs-centralnaBanka/WEB-INF/xml/XWSCentralnaBanka.wsdl",
                  targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/centralna_banka") 
public class XWSCentralnaBankaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ftn.uns.ac.rs/xws/cbs/centralna_banka", "XWSCentralnaBankaService");
    public final static QName XWSCentralnaBankaPort = new QName("http://www.ftn.uns.ac.rs/xws/cbs/centralna_banka", "XWSCentralnaBankaPort");
    static {
        URL url = XWSCentralnaBankaService.class.getResource("/home/nikola/workspace/xws/xws-cbs-centralnaBanka/WEB-INF/xml/XWSCentralnaBanka.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(XWSCentralnaBankaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/home/nikola/workspace/xws/xws-cbs-centralnaBanka/WEB-INF/xml/XWSCentralnaBanka.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public XWSCentralnaBankaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public XWSCentralnaBankaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XWSCentralnaBankaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns XWSCentralnaBanka
     */
    @WebEndpoint(name = "XWSCentralnaBankaPort")
    public XWSCentralnaBanka getXWSCentralnaBankaPort() {
        return super.getPort(XWSCentralnaBankaPort, XWSCentralnaBanka.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XWSCentralnaBanka
     */
    @WebEndpoint(name = "XWSCentralnaBankaPort")
    public XWSCentralnaBanka getXWSCentralnaBankaPort(WebServiceFeature... features) {
        return super.getPort(XWSCentralnaBankaPort, XWSCentralnaBanka.class, features);
    }

}
